### ISSUE TITLE
Error initializing classpath.

### ISSUE THREAD

**Issue by sanjay-shakya** [benorama/grails-cognito-auth#2]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'grails-cognito-auth'.
> > Could not resolve all dependencies for configuration ':runtime'.
>    > Could not find org.grails.plugins:aws-sdk-cognito:2.1.19.

The above message is returned when executing the project locally.

**Comment by musketyr** [comment]
@benorama we're missing a link to Grails Plugins Repository

https://bintray.com/agorapulse/plugins/aws-sdk-cognito#
